# Generated by Django 5.0.2 on 2024-06-29 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StateReview',
            fields=[
                ('StateReview_id', models.AutoField(primary_key=True, serialize=False)),
                ('StateReview_open', models.CharField(max_length=255, null=True)),
                ('Is_active', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('StateReview_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StateReview_User',
            fields=[
                ('StateReview_User_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('StateReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.statereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review_User_History',
            fields=[
                ('Review_User_History_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_review', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to='Review_file/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('StateReview_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.statereview_user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('UserProfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('codename', models.CharField(max_length=255, null=True)),
                ('codeno', models.CharField(max_length=255, null=True)),
                ('bdate', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
