# Generated by Django 5.0.2 on 2024-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statereview',
            name='StateReview_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='statereview',
            name='StateReview_open',
            field=models.DateField(null=True),
        ),
    ]
