# Generated by Django 5.0.2 on 2024-06-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_statereview_statereview_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statereview',
            name='Is_active',
            field=models.BooleanField(null=True),
        ),
    ]
