# Generated by Django 5.0.2 on 2024-06-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_statereview_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_user_history',
            name='status_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statereview',
            name='Is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statereview_user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
