# Generated by Django 5.0.2 on 2024-06-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0004_alter_review_user_history_status_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='User_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
