# Generated by Django 5.0.2 on 2024-07-07 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0006_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('UserProfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('research_field', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('zip_postal_code', models.CharField(max_length=20)),
                ('codename', models.CharField(blank=True, max_length=255, null=True)),
                ('codeno', models.CharField(blank=True, max_length=255, null=True)),
                ('bdate', models.DateField(blank=True, null=True)),
                ('User_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
