# Generated by Django 5.0.2 on 2024-07-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paymet_status',
            field=models.BooleanField(null=True),
        ),
    ]
