# Generated by Django 5.0.2 on 2024-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_userprofile_paymet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statereview_user',
            name='status',
        ),
        migrations.AddField(
            model_name='statereview_user',
            name='Review_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
