# Generated by Django 5.0.2 on 2024-07-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_review_user_history_submition_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statereview',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
