# Generated by Django 5.0.2 on 2024-07-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_statereview_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_user_history',
            name='Submission_Code',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
