# Generated by Django 5.0.2 on 2024-07-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_review_user_history_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_user_history',
            name='Submission_Code',
            field=models.CharField(default=False, max_length=55, null=True),
        ),
    ]
