# Generated by Django 5.0.2 on 2024-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_review_user_history_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_user_history',
            name='status_review',
            field=models.BooleanField(null=True),
        ),
    ]
