# Generated by Django 3.1.14 on 2024-10-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_review_user_history_status_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_info',
            field=models.FileField(null=True, upload_to='Review_file/'),
        ),
    ]
